name: 'Release'
on:
  push:
    branches:
      - master
jobs:
  main:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'chore(release):')"
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Setup git
        env:
          CI_USER: ${{ secrets.CI_GIT_USER }}
          CI_EMAIL: ${{ secrets.CI_GIT_EMAIL }}
        run: |
          git config --local user.email "$CI_EMAIL"
          git config --local user.name "$CI_USER"

      - name: Install dependencies
        run: npm ci

      - name: Generate artifacts
        run: npm run release

      - name: Push changes
        env:
          CI_USER: ${{ secrets.CI_GIT_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push "https://$CI_USER:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git" HEAD:master --follow-tags

      - name: Update labels
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx github-label-setup --token $GITHUB_TOKEN
